apiVersion: 1

datasources:
  - name: Coordinator-Graph
    uid: coordinator-graph
    type: marcusolsson-json-datasource
    access: proxy
    url: http://coordinator:8000
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      queryParams: ""
    secureJsonData:
      basicAuthPassword: admin-dev
    editable: true
