heartbeat_interval_seconds: 300
spec_validity_seconds: 120
peer_count_per_probe: 3
peer_interval_seconds: 300
registration_keys:
- dev-registration-key
builtin_measurements:
- id: builtin-ping-ad
  type: icmp_ping
  target: knet.ad.svenskakyrkan.se
  interval_seconds: 60
  packet_count: 4
  resolve_on_probe: true
- id: builtin-ping-gateway
  type: icmp_ping
  target: 1.1.1.1
  interval_seconds: 60
  packet_count: 4
  resolve_on_probe: false
- id: builtin-tcp-smtp
  type: tcp_ping
  target: smtp.svenskakyrkan.se
  port: 25
  interval_seconds: 60
- id: builtin-dns
  type: dns_query
  target: 10.60.0.11
  query_name: kornet.svenskakyrkan.se
  query_type: A
  interval_seconds: 300
- id: builtin-http-kob
  type: http_get
  target: https://kob.svenskakyrkan.se
  interval_seconds: 60
  expect_status: 200
- id: builtin-traceroute-kob
  type: traceroute
  target: kob.svenskakyrkan.se
  interval_seconds: 600
  max_hops: 20
canary_targets:
- target: knet.ad.svenskakyrkan.se
  description: AD-DC
- target: smtp.svenskakyrkan.se
  description: SMTP-server
nkn_public_ip_ranges:
- 195.67.168.0/22
